---
- name: Set MOTD on Cisco Router
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    
  tasks:
    - name: Set MOTD banner on Cisco router
      cisco.ios.ios_banner:
        banner: motd
        text: "{{ custom_motd }}"
        state: present
      register: banner_result

    - name: Save configuration
      cisco.ios.ios_config:
        save_when: modified
      when: banner_result.changed
